// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXB1R8kBu2ZaMg8LTHe_b5dei4m7-KR1A',
    appId: '1:127017405817:web:8020246bb0b2501dfff3a8',
    messagingSenderId: '127017405817',
    projectId: 'sentix-ab435',
    authDomain: 'sentix-ab435.firebaseapp.com',
    storageBucket: 'sentix-ab435.firebasestorage.app',
    measurementId: 'G-FCJ3FDJMMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4OL5ogUHhJd49FMkqcZcj1pcVfMc6dU',
    appId: '1:127017405817:android:67bae3a1c911466ffff3a8',
    messagingSenderId: '127017405817',
    projectId: 'sentix-ab435',
    storageBucket: 'sentix-ab435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQqQkt-cf_KnfoEijdeOsL9hhFqnNu-80',
    appId: '1:127017405817:ios:4bf1c260a583167afff3a8',
    messagingSenderId: '127017405817',
    projectId: 'sentix-ab435',
    storageBucket: 'sentix-ab435.firebasestorage.app',
    iosBundleId: 'com.example.sentix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQqQkt-cf_KnfoEijdeOsL9hhFqnNu-80',
    appId: '1:127017405817:ios:4bf1c260a583167afff3a8',
    messagingSenderId: '127017405817',
    projectId: 'sentix-ab435',
    storageBucket: 'sentix-ab435.firebasestorage.app',
    iosBundleId: 'com.example.sentix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXB1R8kBu2ZaMg8LTHe_b5dei4m7-KR1A',
    appId: '1:127017405817:web:0bfca1314497e00bfff3a8',
    messagingSenderId: '127017405817',
    projectId: 'sentix-ab435',
    authDomain: 'sentix-ab435.firebaseapp.com',
    storageBucket: 'sentix-ab435.firebasestorage.app',
    measurementId: 'G-GHC796J7LD',
  );
}
